### PR TITLE
Clintlemons forLoop assignment

### PR DESCRIPTION
**Pull request by clintlemons**

### CODE REVIEW

**Comment by cpfiles** [comment]
Your program does not print any of the lines it needs to. It is mostly because you have semi-colons after your if statements. Have a look and if you can, fix it before the deadline.

**Comment by cpfiles** [comment]
Clint, it still does not work. We can go over how to do it correctly during the lab tonight.

**Comment by clintlemons** [comment]
Ok sounds good, thanks for looking over it.

**Comment by clintlemons** [comment]
Submitting corrections.

**Comment by cpfiles** [comment]
Glad you got this working! Do pay attention to your formatting though.

**Pull request closed without merging**
