### PR TITLE
Sethdumas

### PR DESCRIPTION
**Pull request by sethdumas**

### CODE REVIEW

**Comment by cpfiles** [comment]
I do not see your code. Did you commit and push before you made the pull request?

**Comment by sethdumas** [comment]
That's odd. I know I committed and pushed before I did the pull request on
Saturday night. Do you want me to try again now or wait till we get to
class?

**Comment by cpfiles** [comment]
Please try again if you have time. Here is what I see in your branch: https://github.com/cpfiles/aca2016/tree/sethdumas/ACA2016/src/edu/uca/aca2016

**Comment by cpfiles** [comment]
Excellent.

1. Some of your formatting is off. You also need to add your javadoc comments.

**Pull request merged**
