### PR TITLE
Clintlemons

### PR DESCRIPTION
**Pull request by clintlemons**
Assignment 002

### CODE REVIEW

**Comment by cpfiles** [comment]
Your Automobile and Team classes are not in the project.

**Comment by clintlemons** [comment]
Yikes!  I found both in the recycle bin within the directory we replaced to
get my NetBeans working last night.  How would I go about restoring those
files?  Thanks!

**Comment by cpfiles** [comment]
1. Check out your branch.
2. Copy the files into the correct location. They should then appear in Netbeans.
3. Make sure everything works.
4. Commit and Push to Upstream

**Comment by cpfiles** [comment]
Unsatisfactory.

1. Your coded for this assignment ended up in your branch for the next assignment. I will fix the git tree. Be careful about where you store and push your code. Not an assignment issue, just wanted you to be aware.
2. In your Runner class you altered the `main` method. Doing this makes your program fail to run. `main(String[] args, Automobile Automobile)` should be `main(String[] args)`
3. You never properly initialized an `Automobile` class and printed its properties.
4. Several of your methods still contain the `UnsupportedOperationException` exception and do not work. This includes some of the constructors.

If you want to see how this was suppose to work you can look through your classmate's code. I can also go over this with you during the lab tomorrow if you want.

**Pull request closed without merging**
